/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Veterinario;
import javax.swing.table.DefaultTableModel;
import controladores.ConsultaControlador;
import controladores.MascotaControlador;
import java.time.LocalDate;
import java.util.ArrayList;
import modelo.Consulta;
import modelo.Mascotas;

/**
 *
 * @author Kevin
 */
public class VentanaMedicina extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMedicina.class.getName());
    private ConsultaControlador controladorConsulta ;
    private VentanaServicios ventanaServicios;
    private MascotaControlador controladorMascota;
    
    public VentanaMedicina(VentanaServicios ventanaServicios,MascotaControlador controladorMascota) {
        this.ventanaServicios = ventanaServicios;
        this.controladorMascota = controladorMascota;
        this.controladorConsulta = new ConsultaControlador();
        initComponents();
        setTitle("Gestion de Consultas");
        setLocationRelativeTo(this);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Especialidad");
        Veterinario vet1 = new Veterinario("Dra. Ana Gómez", "Medicina Interna");
        Veterinario vet2 = new Veterinario("Dr. Luis Torres", "Cirugía");
        modelo.addRow(new Object[]{vet1.getNombre(),vet1.getEspecialidad()});
        modelo.addRow(new Object[]{vet2.getNombre(),vet2.getEspecialidad()});
        tablaMedicina.setModel(modelo);
        DefaultTableModel modeloCons = new  DefaultTableModel(new Object[]{"Fecha", "Codigo", "Nombre Mascota", "Documento propietario"
        , "Nombre Veterinario","Especialidad Veterinario", "Diagnostico","Tratamiento"}, 0);
        tablaConsulta.setModel(modeloCons);
    }
    
    public void ListarConsulta(){
            String[] columnas = {"Fecha", "Codigo", "Nombre Mascota", "Documento propietario"
        , "Nombre Veterinario","Especialidad Veterinario", "Diagnostico","Tratamiento"};
          DefaultTableModel modeloCons = new DefaultTableModel(columnas, 0);
          ArrayList<Consulta> c = controladorConsulta.obtenerConsultas();
          if(c != null &&  !c.isEmpty())
          for(Consulta cons : c){
               Object[] fila = {cons.getFecha(),cons.getCodigo(),cons.getNombreMasCons(),
               cons.getDocumentoPropCons(),cons.getVeterinario().getNombre(),cons.getVeterinario().getEspecialidad()
               ,cons.getDiagnostico(),cons.getTratamiento()};
              
          modeloCons.addRow(fila);
          }
         tablaConsulta.setModel(modeloCons);
    }

            
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMedicinaNomProp = new javax.swing.JTextField();
        txtMedicinaIdMas = new javax.swing.JTextField();
        txtMedicinaCodigo = new javax.swing.JTextField();
        txtMedicinaTartamiento = new javax.swing.JTextField();
        txtMedicinaDiagnostico = new javax.swing.JTextField();
        btnMedicinaGurdar = new javax.swing.JButton();
        comboboxVet = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicina = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 210, 197));

        jPanel1.setBackground(new java.awt.Color(132, 169, 140));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medicina");

        jLabel2.setText("Documento Propietario:");

        jLabel3.setText("Id de la Mascota:");

        jLabel4.setText("Codigo:");

        jLabel5.setText("Nombre Veterinario:");

        jLabel6.setText("Tratamiento:");

        jLabel7.setText("Diagnostico:");

        txtMedicinaNomProp.setText("jTextField1");
        txtMedicinaNomProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicinaNomPropActionPerformed(evt);
            }
        });

        txtMedicinaIdMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicinaIdMasActionPerformed(evt);
            }
        });

        txtMedicinaCodigo.setText("jTextField3");

        txtMedicinaTartamiento.setText("jTextField5");

        txtMedicinaDiagnostico.setText("jTextField6");

        btnMedicinaGurdar.setText("jButton1");
        btnMedicinaGurdar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinaGurdarActionPerformed(evt);
            }
        });

        comboboxVet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tablaMedicina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMedicina);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMedicinaNomProp)
                        .addComponent(txtMedicinaIdMas)
                        .addComponent(txtMedicinaCodigo)
                        .addComponent(txtMedicinaTartamiento)
                        .addComponent(txtMedicinaDiagnostico))
                    .addComponent(comboboxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMedicinaGurdar)
                        .addGap(173, 173, 173))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMedicinaNomProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMedicinaIdMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMedicinaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboboxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMedicinaTartamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMedicinaDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMedicinaGurdar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de Consulta", jPanel3);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaConsulta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gestion de Consultas", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicinaNomPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicinaNomPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicinaNomPropActionPerformed

    
  
    
    private void btnMedicinaGurdarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinaGurdarActionPerformed
    int idMas = Integer.parseInt(txtMedicinaIdMas.getText());
    String codigo = txtMedicinaCodigo.getText();
    String tratamiento = txtMedicinaTartamiento.getText();
    String diagnostico = txtMedicinaDiagnostico.getText();
    int fila = tablaMedicina.getSelectedRow();
    
    if( idMas <= 0  || codigo == null || codigo.isBlank()||tratamiento == null
    ||tratamiento.isBlank() || diagnostico == null || diagnostico.isBlank()){
      JOptionPane.showMessageDialog(this, " Porfavor completar todos los campos de manera correcta.", "Error", JOptionPane.ERROR_MESSAGE);
      return;
    }
    
    if(fila == -1){
        JOptionPane.showMessageDialog(this, "Porfavor selecciona un veterinario para continuar con el registro");
        return;
}  
    Mascotas m = controladorMascota.buscarMascota(idMas);
    if(m == null){
        JOptionPane.showMessageDialog(this, "No existe la mascota con el id:" + idMas);
        return;
    }    
    
      String nombre = tablaMedicina.getValueAt(fila, 0).toString();
      String especialidad = tablaMedicina.getValueAt(fila, 1).toString();
      Veterinario vetFin = new Veterinario(nombre, especialidad);

      Consulta confirmar = controladorConsulta.buscarConsulta(codigo);
      if(confirmar == null){
         controladorConsulta.registrarConsulta(codigo, LocalDate.now().toString(), vetFin, m.getDocumentoProp(), m.getNombre(), diagnostico, tratamiento);
          ListarConsulta();
         JOptionPane.showMessageDialog(this, "La consulta se guardo correctamente.");
}else{
          JOptionPane.showMessageDialog(this, "La consulta no se pudo registrar, ya existe una con la misma informacion.");

              }


    
    
    





    }//GEN-LAST:event_btnMedicinaGurdarActionPerformed

    private void txtMedicinaIdMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicinaIdMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicinaIdMasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new VentanaMedicina().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMedicinaGurdar;
    private javax.swing.JComboBox<String> comboboxVet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaConsulta;
    private javax.swing.JTable tablaMedicina;
    private javax.swing.JTextField txtMedicinaCodigo;
    private javax.swing.JTextField txtMedicinaDiagnostico;
    private javax.swing.JTextField txtMedicinaIdMas;
    private javax.swing.JTextField txtMedicinaNomProp;
    private javax.swing.JTextField txtMedicinaTartamiento;
    // End of variables declaration//GEN-END:variables
}
